function eggers5(fname)
% EGGERS5(fname)
%
% Makes FIGURE 5 of Olhede et al. (2017), illustrating the empirical
% performance of estimating the parameters of an isotropic Matern process
% (variance, differentiability, range). The data plotted in this figure are
% generated by this program via invoking MLEOSL('demo1'), where important
% things are happening, and which you need to study internally. The plot
% itself is generated by invoking MLEOSL('demo2',...) with the name of the
% saved data, which then calls MLEPLOS, and so on.
%
% INPUT
%
% fname    The full file name to a previously saved run
%
% Tested on 8.3.0.532 (R2014a) and 9.0.0.341360 (R2016a)
% Last modified by fjsimons-at-alum.mit.edu, 10/13/2016 

% We developed this using
% fname='16-Jun-2015-64-2' 

% If you've ran anything before, it will try to plot the results
defval('fname','30-Sep-2016');

try 
  % Remember that you can get some output from the below
  mleosl('demo2',fname)
catch
  % Number of processors, must agree with your machine
  NumWorkers=8;
  if isempty(gcp('nocreate')); pnw=parpool(NumWorkers); end
  
  % Matern parameters, in standard units
  % The parameters for the top row in the published work
  th0=[1e6 2.5 2e4];
  fields=   {'dydx',     'NyNx','blurs','kiso','quart'};
  defstruct('params',fields,...
            {[10 10]*1e3,[64 64],-1      ,NaN,   0});
  
  % Running the thing on multiple processors
  spmd
    % Second argument is number of simulations
    % Third argument is the Matern parameter set
    % Fourth argument is the experimental parameter set
    % Fifth argument is the experimental parameter set
    mleosl('demo1',20,th0,params,'unc')
    % Note that on fast machines the writing of the diagnos file may not
    % be kept up, mixing between notes, and I've been hand-fixing that
  end
end



