function eggers4
% EGGERS4
%
% Makes FIGURE 3 of Olhede et al. (2017), illustrating the empirical
% performance of two ways of estimating the variance of and isotropic Matern
% process, as a function of its parameters (variance, differentiability,
% range) and for a suite of field sizes. The 'poor' way is simply the
% sample variance, whereas the 'mle' way refers to the maximum-likelihood
% estimation procedure. The data plotted in this figure are generated by
% invoking SIMULOSL('demo4'). 
%
% Tested on 8.3.0.532 (R2014a) and 9.0.0.341360 (R2016a)
% Last modified by fjsimons-at-alum.mit.edu, 09/19/2016

% Metric conversion
mfromkm=1000;

% Matern parameters, in standard units
% The parameters for the first row
th0t=[1e6 2.5 2e4];
% th0t=[1e6 2.0 5e4]; % Have done but need to adjust varbias
% The parameters for the second row
th0b=[1e6 2.5 4e4];
% th0b=[1e6 3.0 10e4]; % Have done but need to adjust varbias

% Experimental parameters
fields={'dydx','NyNx','blurs','kiso','quart'};
defstruct('params',fields,{[10 10]*1e3,[64 64],-1,NaN,0})
% Maximum field size and discretization of the sizes tried
N=128; rindj=[2:2:N];

% Number of simulations per processor, higher is better for small grids
npr=5;
% Number of processors, must agree with your machine and SIMULOSL
NumWorkers=8;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Prepare the figure: four panels with different parameters
clf; [ah,ha,H]=krijetem(subnum(2,2));

% A brute-force case
axes(ah(1))
[gane,miy,ax(1),legs]=...
    simulosl('demo4',th0t,params,'poor',N,rindj,npr,ah);

% Figure out a good legend
if 1==1
  leg=legend(legs,...
             sprintf('mean (%i%s)',...
                     npr*NumWorkers,'\times'),...
             'predicted',...
             '5-95 perc',...
             'single run',...
             'covariance',...
             'Location','SouthEast');
end

% A maximum-likelihood case
axes(ah(2))
[~,~,ax(2)]=...
    simulosl('demo4',th0t,params,'mle',N,rindj,npr,ah,gane,miy);

% Meaningful title
tl(1)=supertit(ah(1:2),sprintf('%s = %3.1f km ; %s = %3.1f ; %s = %i km',...
			'\sigma',sqrt(th0t(1))/mfromkm,...
			'\nu',th0t(2),...
			'\rho',th0t(3)/mfromkm));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Another brute-force case
axes(ah(3))
[gane,miy,ax(3)]=...
    simulosl('demo4',th0b,params,'poor',N,rindj,npr,ah);

% Another maximum-likelihood case
axes(ah(4))
[~,~,ax(4)]=...
    simulosl('demo4',th0b,params,'mle',N,rindj,npr,ah,gane,miy);

% Meaningful title
tl(2)=supertit(ah(3:4),sprintf('%s = %3.1f km ; %s = %3.1f ; %s = %i km',...
			'\sigma',sqrt(th0b(1))/mfromkm,...
			'\nu',th0b(2),...
			'\rho',th0b(3)/mfromkm));

% Slap some boxes on the panels
[bh(1),th(1)]=boxtex('ur',ah(2),'MLE',10,1,1,1.1);
[bh(2),th(2)]=boxtex('ur',ah(4),'MLE',10,1,1,1.1);

% Cosmetics to match EGGERS1 exactly
movev(tl(1),-0.31)
movev(tl(2),+0.14)
set(ah,'ygrid','on','box','on')
set(tl,'FontSize',12)
for ind=1:length(ah); yl(ind)=get(ah(ind),'ylabel'); end
for ind=1:length(ah); xl(ind)=get(ah(ind),'xlabel'); end
nolabels(ha([3 4]),2); delete(yl([2 4]))
nolabels(ah([1 2]),1); delete(xl([1 2]))
serre(H,[],'across'); serre(H',1/3,'down')
% Do something with them? Nah, forget
Hx=reshape(ax,2,2)'; delete(Hx); 

% Print to file
fig2print(gcf,'portrait')
figdisp([],[],[],2,'epsc','epstopdf');
